<?php

namespace ExtendedDocument\APIBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function getDocumentsByDate($type)
    {
        return $this->_em->createQuery('
SELECT d
FROM ExtendedDocument\APIBundle\Model\Document d
')
            ->getResult();
    }*/
}
