<?php

namespace ExtendedDocument\APIBundle\Repository;

/**
 * MetadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetadataRepository extends \Doctrine\ORM\EntityRepository
{
}
