<?php

namespace ExtendedDocument\APIBundle\Repository;

/**
 * VisualizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisualizationRepository extends \Doctrine\ORM\EntityRepository
{
}
