extended_document_api_homepage:
    path:     /
    defaults: { _controller: ExtendedDocumentAPIBundle:Default:index }

addDocument:
    path:     /addDocument
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:addDocument }

editDocument:
    path:     /editDocument/{idDocument}
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:editDocument }

deleteDocument:
    path:     /deleteDocument/{idDocument}
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:deleteDocument }

getDocument:
    path:     /getDocument/{idDocument}
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:getDocument }

getDocuments:
    path:     /getDocuments
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:getDocuments }

displayDocuments:
    path:     /displayDocuments
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:displayDocuments }