extended_document_api_homepage:
    path:     /
    defaults: { _controller: ExtendedDocumentAPIBundle:Default:index }

addDocument:
    path:     /addDocument
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:addDocument }

editDocument:
    path:     /editDocument/{idDocument}
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:editDocument }

deleteDocument:
    path:     /deleteDocument/{idDocument}
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:deleteDocument }

getDocument:
    path:     /getDocument/{idDocument}
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:getDocument }

getDocuments:
    path:     /getDocuments
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:getDocuments }

getDocumentsByRadius:
    path:     /getDocumentsByRadius/{x}/{y}/{radius}/{limit}
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:getDocumentsByRadius, x:0, y:0, limit:-1, radius:-1}

getDocumentsByDate:
    path:     /getDocumentsByDate/{type}/{date1}/{date2}
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:getDocumentsByDate, date2:null}

displayDocuments:
    path:     /displayDocuments
    defaults: { _controller: ExtendedDocumentAPIBundle:Document:displayDocuments }